# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: NONE

[toolchain]
channel = "nightly-2024-05-11"
components = ["clippy", "rust-analyzer", "rustfmt"]
targets = ["x86_64-unknown-uefi"]
profile = "minimal"
