# SPDX-License-Identifier: GPL-3.0-only
# SPDX-FileCopyrightText: 2024 System76, Inc.

[package]
name = "system76-gop-policy"
version = "1.0.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
redox_uefi_std.workspace = true
