# SPDX-License-Identifier: CC0-1.0
# SPDX-FileCopyrightText: NONE

name: CI
on:
  push:
    branches-ignore:
    - 'wip/*'
  pull_request:

env:
  CARGO_TERM_COLOR: always
  # TODO: Update gop-policy to not require embedded file set from env var
  FIRMWARE_OPEN_VBT: "../lemp9.vbt"

jobs:
  lint:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - run: rustup show active-toolchain || rustup toolchain install
    - run: cargo fetch --locked
    - run: cargo fmt --check
    - run: cargo clippy -- -D warnings

  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - run: rustup show active-toolchain || rustup toolchain install
    - run: cargo fetch --locked
    - run: cargo xtask build
